DOCUMENTS_DIRECTORY = "documents"
PERSIST_DIRECTORY = "chroma_db"
COLLECTION_NAME = "enterprise_documents"

EMBEDDING_MODEL = "nomic-embed-text"
CHAT_MODEL = "llama3.2:3b"

CHUNK_SIZE = 1200
CHUNK_OVERLAP = 200

TOP_K = 4


PARENT_CHUNK_SIZE = 2000
PARENT_CHUNK_OVERLAP = 200

CHILD_CHUNK_SIZE = 400
CHILD_CHUNK_OVERLAP = 80

PARENT_RETRIEVAL_TOP_K = 4